# Generated by Django 4.2.25 on 2025-10-22 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_testimonial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='rating',
        ),
    ]
